### ISSUE TITLE
add example of taxonomic authority description

### ISSUE THREAD

**Issue by sformel-usgs** [ESIPFed/bds-primer-best-practices#13]
**What section of the best practices does your suggestion relate to?**
section 6.4.2 Match scientific names to a taxonomic authority: key information

**Short description of content that should be added**
bullet point 1 says "include the authority who manages said information in your metadata".  Need an example of what this looks like.

**Content to add**
Still working on ideas.  From Margaret O'Brien: Here is the git issue where we tried to tackle this for EML:
 https://github.com/PASTAplus/DataPortal/issues/7
https://github.com/lter/LTER-core-metabase/issues/89

there are links within these to the discussion of taxon in EML metadata in general

**Comment by lbrensk11** [comment]
Definition: As used here, a taxonomic authority is an online resource that maintains up-to-date species-level classification information and provides persistent identifiers for taxonomic classifications.
Example: For the species _Balaenoptera borealis_ (Lesson, 1828), the WoRMS taxonomic authority ID link is https://www.marinespecies.org/aphia.php?p=taxdetails&id=137088 and the LSID is urn:lsid:marinespecies.org:taxname:137088.

Is this what we are looking for in terms of an example?

**Comment by sformel-usgs** [comment]
@lbrensk11 Perfect, thank you!  FYI, you can trigger actions along with pull requests to close issues, so you don't have to manually link them.  See here: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
