### ISSUE TITLE
change title of lat/lon section

### ISSUE THREAD

**Issue by sformel-usgs** [ESIPFed/bds-primer-best-practices#4]
**What section of the best practices does your suggestion relate to?**
Section 6.5 Record latitude and longitude in decimal degrees in WGS84

**Short description of content that should be revised**
Section title should be changed to be less imposing.

**Suggested revision**
Provide latitude and longitude in decimal degrees in WGS84

**Comment by sformel-usgs** [comment]
From Matt Biddle: I get nervous about the WGS84 part - could we just say define the datum used with a preference?

**Comment by sformel-usgs** [comment]
From Margaret O'Brien via google doc: It also depends on how that lat-lon will be used. e.g, for basic mapping in high level metadata, a simple decimal latlon is what you need (e.g., for a google map pin). in data, actual use might require the projection for analysis.

**Comment by albenson-usgs** [comment]
Primer changed but leaving open until we meet with Matt Biddle.

**Comment by MathewBiddle** [comment]
Docs Section:
https://github.com/ESIPFed/bds-primer-best-practices/blob/6f3b0266a881067680206a312f4533f0057c1be2/content/6-SOFTWARE_READY.Rmd#L164-L220

My main concern with this is it is specifically calling out WGS84. I think it should state "identify the geodetic datum used" as other datums are acceptable, we just need to know what is used for the coordinates. With that being said, making that adjustment means we would have to provide more information as to what a geodetic datum is and how to document it. Which would conflate the document.

I'm not sure what the right approach is here. 

Below is my recommendation:

**Suggested revision**
Title: Provide latitude and longitude in decimal degrees including geodetic datum information.

[line 179](https://github.com/ESIPFed/bds-primer-best-practices/blob/6f3b0266a881067680206a312f4533f0057c1be2/content/6-SOFTWARE_READY.Rmd#LL179C1-L179C118) - If possible, encourage data providers to confirm, and record, the datum prior to data collection **(WGS84 recommended)**.

**Comment by albenson-usgs** [comment]
My issue with that is that we would then need to explain what a geodetic datum is as I don't think that's a term that everyone will be familiar with. In my view, we don't have the space to explain geodetic datum in the best practice and to me a google search for "WGS84" leads to more intuitive results for someone that is unfamiliar than a search for "geodetic datum" will.

**Comment by sformel-usgs** [comment]
I understand both of your concerns.  How's this for trying to bridge the gap? It references a GIS-specific wiki page that is different from Matt's link above:

- [line 179](https://github.com/ESIPFed/bds-primer-best-practices/blob/6f3b0266a881067680206a312f4533f0057c1be2/content/6-SOFTWARE_READY.Rmd#LL179C1-L179C118) - If possible, encourage data providers to confirm, and record, the datum prior to data collection. 
   - The three most commonly used datums are WGS84, NAD83, and NAD27. A more complete list can be found here: https://wiki.gis.com/wiki/index.php/Datum_(geodesy)#List_of_Datums
   - WGS84 is the default for many consumer-grade tools that biologists may rely on, like Garmin GPS units and Google Maps.

**Comment by sformel-usgs** [comment]
As discussed at co-chair meeting, we'll leave the WGS84 in the title for now, add a link to the references, and see how things develop.
