### ISSUE TITLE
add graphic of precision for coordinates

### ISSUE THREAD

**Issue by sformel-usgs** [ESIPFed/bds-primer-best-practices#5]
**What section of the best practices does your suggestion relate to?**
Section 6.5.3 Record latitude and longitude in decimal degrees in WGS84: references

**Short description of content that should be added**
would be nice to include a graphic to depict precision

**Content to add**
Something like this http://wiki.gis.com/wiki/index.php/Decimal_degrees

**Comment by sformel-usgs** [comment]
After looking at many charts and graphics, I couldn't land on anything that I thought added much to the module.  I did include this chart as a reference for now.  @MathewBiddle you got strong feelings on this one?

**Comment by MathewBiddle** [comment]
I think the xkcd graphic is sufficient.  I think it's already linked in the docs.

https://imgs.xkcd.com/comics/coordinate_precision.png

https://github.com/ESIPFed/bds-primer-best-practices/blob/6f3b0266a881067680206a312f4533f0057c1be2/content/6-SOFTWARE_READY.Rmd#L166C6-L170
